import { Banner } from '@/components'
import ProductsComponent from '@/components/Products'
import SelectTemplate from '@/components/SelectTemplate'
import axios from 'axios'
import { GetServerSideProps, Metadata } from 'next'
import React from 'react'

type Props = {
}
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
const MyApp: React.FC<Props> = () => {
    return <SelectTemplate />
}

export default MyApp